const fakePEM =
      "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVeARtBQ+epdTqoyWX/swUvs8K2tGVl7atzUlkJ9aa9CgCgYIKoZIzj0DAQehRANCAAQ9tUaiokvokpFX7qjE6F99TxgyHb970+bX5YmdZmiC3u+aMlkjLvzf74pyveOT5kFp5Hv4x+3OZENJMymzVZMd\n-----END PRIVATE KEY-----";
